### ISSUE TITLE
`polymerize init` with Git repos is broken

### ISSUE THREAD

**Issue by kirbyfan64** [polymer-dart/polymerize#9]
Basically, if you have something like this in `pubspec.yaml`:

```yaml
dependency_overrides:
  mypackage:
    git: some-url
```

`polymerize` will end up trying to use [a tag named HEAD](https://github.com/polymer-dart/polymerize/blob/master/lib/src/init_command.dart#L55), which doesn't exist, thereby making Bazel get confused and abort. Yay. :/
